var tokenRules = {
    "while": /while/,
    "volatile": /volatile/,
    "void": /void/,
    "unsigned": /unsigned/,
    "union": /union/,
    "typedef": /typedef/,
    "switch": /switch/,
    "struct": /struct/,
    "static": /static/,
    "sizeof": /sizeof/,
    "signed": /signed/,
    "short": /short/,
    "return": /return/,
    "register": /register/,
    "long": /long/,
    "int": /int/,
    "if": /if/,
    "goto": /goto/,
    "for": /for/,
    "float": /float/,
    "extern": /extern/,
    "enum": /enum/,
    "else": /else/,
    "double": /double/,
    "do": /do/,
    "default": /default/,
    "continue": /continue/,
    "const": /const/,
    "char": /char/,
    "case": /case/,
    "break": /break/,
    "auto": /auto/,
    "whitespace": /[ \t\v\n\f]/,
    "unmatched": /./
};
module.exports.tokenRules = tokenRules;
