        var conditional_expr = require("../../lib/rules.js").conditional_expr;
        var arrow = { "pointer": 0};
        var token_stream = [ 
          { lexeme: '(',
            row: 1,
            col: 1,
            tokenClass: '(',
            parent: null,
            children: null },
          { lexeme: '(',
            row: 1,
            col: 2,
            tokenClass: '(',
            parent: null,
            children: null },
          { lexeme: '1',
            row: 1,
            col: 3,
            tokenClass: 'CONSTANT',
            parent: null,
            children: null },
          { lexeme: '<',
            row: 1,
            col: 5,
            tokenClass: '<',
            parent: null,
            children: null },
          { lexeme: '2',
            row: 1,
            col: 7,
            tokenClass: 'CONSTANT',
            parent: null,
            children: null },
          { lexeme: ')',
            row: 1,
            col: 8,
            tokenClass: ')',
            parent: null,
            children: null },
          { lexeme: '?',
            row: 1,
            col: 10,
            tokenClass: '?',
            parent: null,
            children: null },
          { lexeme: '1',
            row: 1,
            col: 12,
            tokenClass: 'CONSTANT',
            parent: null,
            children: null },
          { lexeme: ':',
            row: 1,
            col: 14,
            tokenClass: ':',
            parent: null,
            children: null },
          { lexeme: '2',
            row: 1,
            col: 16,
            tokenClass: 'CONSTANT',
            parent: null,
            children: null },
          { lexeme: ')',
            row: 1,
            col: 17,
            tokenClass: ')',
            parent: null,
            children: null } 
        ];

        resulting_json = conditional_expr(token_stream, arrow);
